# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      # - name: Automated Version Bump
      #   uses: phips28/gh-action-bump-version@v9.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     skip-tag: "true"

      # - uses: azure/login@v1
      #   with:
      #       creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: dist
          container_name: $web
          connection_string: ${{ secrets.shackletonmedia }}
          sync: true
    # - name: Purge CDN endpoint
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.0.72
    #     inlineScript: |
    #        az cdn endpoint purge --content-paths  "/*" --profile-name "Shackleton" --name "shackleton" --resource-group "MediaConversion"
  # Azure logout
  # - name: logout
  #   run: |
  #         az logout
  #   if: always()
